In [13]:
import pandas as pd
import numpy as np
import os

In [14]:
"""
Provides screening days analysis of the data in the CSV file. The format of the CSV file is as follows:
```
cinema,date,title_excerpt,url
Метрополь,01.09.1953,"АРЕНА СМЕЛЫХ",https://electro.nekrasovka.ru/books/6173751/pages/4
Метрополь,01.09.1953,"ПАРМСКАЯ ОБИТЕЛЬ (1-я серия)",https://electro.nekrasovka.ru/books/6173751/pages/4
Метрополь,01.09.1953,"ЧУК И ГЕК",https://electro.nekrasovka.ru/books/6173751/pages/4
Ударник,01.09.1953,"ПАРМСКАЯ ОБИТЕЛЬ (1-я серия)",https://electro.nekrasovka.ru/books/6173751/pages/4
Ударник,01.09.1953,"ПРАЗДНИК СВ. ИОРГЕНА",https://electro.nekrasovka.ru/books/6173751/pages/4
Орион,01.09.1953,"ПАРМСКАЯ ОБИТЕЛЬ (1-я серия)",https://electro.nekrasovka.ru/books/6173751/pages/4
```
"""

'\nProvides screening days analysis of the data in the CSV file. The format of the CSV file is as follows:\n```\ncinema,date,title_excerpt,url\nМетрополь,01.09.1953,"АРЕНА СМЕЛЫХ",https://electro.nekrasovka.ru/books/6173751/pages/4\nМетрополь,01.09.1953,"ПАРМСКАЯ ОБИТЕЛЬ (1-я серия)",https://electro.nekrasovka.ru/books/6173751/pages/4\nМетрополь,01.09.1953,"ЧУК И ГЕК",https://electro.nekrasovka.ru/books/6173751/pages/4\nУдарник,01.09.1953,"ПАРМСКАЯ ОБИТЕЛЬ (1-я серия)",https://electro.nekrasovka.ru/books/6173751/pages/4\nУдарник,01.09.1953,"ПРАЗДНИК СВ. ИОРГЕНА",https://electro.nekrasovka.ru/books/6173751/pages/4\nОрион,01.09.1953,"ПАРМСКАЯ ОБИТЕЛЬ (1-я серия)",https://electro.nekrasovka.ru/books/6173751/pages/4\n```\n'

In [15]:
# Turns on step-wise logging
verbose_logging = True
# Location where the CSV file with screening days analysis is stored (see the last code block)
save_filepath = './results/screening.csv'

In [16]:
def get_data(csv_filepath: str) -> pd.DataFrame:
    """
    Reads a CSV file from the given filepath and returns it as a pandas DataFrame.

    Args:
        csv_filepath (str): The path to the CSV file.

    Returns:
        pd.DataFrame: The data from the CSV file as a pandas DataFrame.
    """
    data = pd.read_csv(csv_filepath)
    return data

In [17]:
filepath = './results/schedule.csv'
data = get_data(filepath)
data = data[['cinema', 'date', 'title_excerpt']]
data = data.rename(columns={'title_excerpt': 'title'})
data.head()

         cinema        date               title
0    Стереокино  01.06.1953      «МАЙСКАЯ НОЧЬ»
1  Юный зритель  02.06.1953         «ЧУК И ГЕК»
2    Стереокино  02.06.1953      «МАЙСКАЯ НОЧЬ»
3  Юный зритель  03.06.1953         «ЧУК И ГЕК»
4         Искра  04.06.1953  «ОПАСНОЕ СХОДСТВО»

In [18]:
titles = data.groupby('title').count()
titles

                      cinema  date
title
«АДМИРАЛ УШАКОВ»           1     1
«АЛЕКСАНДР НЕВСКИЙ»        1     1
«АНГЕЛ В ОТПУСКЕ»          2     2
«АРЕНА СМЕЛЫХ»             6     6
«АРШИН МАЛ АЛАН»           2     2
...                      ...   ...
«ЧЕТВЕРТЫЙ ПЕРИСКОП»       1     1
«ЧОРТОВО УЩЕЛЬЕ»           2     2
«ЧУК И ГЕК»               16    16
«ШКОЛА НЕНАВИСТИ»          1     1
«ЮНОСТЬ ПОЭТА»             1     1

[61 rows x 2 columns]

In [19]:
screening_info = []


for (cinema, title), group in data.groupby(['cinema', 'title']):
    group['date'] = pd.to_datetime(group['date'], format='%d.%m.%Y')
    group = group.sort_values(by='date')

    last_date_included = -1

    for i, (row_index, row) in enumerate(group.iterrows()):
        if (last_date_included != -1) and (row['date'] - last_date_included).days <= 0:
            continue

        prev_date = row['date']
        screening_days = 0

        next_rows = group.loc[row_index:, ['cinema', 'date', 'title']]

        for _, row2 in next_rows.iterrows():
            if (row2['cinema'] != cinema) or (row2['title'] != title):
                break

            # we expect to count the current row as well (thus, <= 1), since it is included into next_rows
            if (row2['date'] - prev_date).days <= 1:
                prev_date = row2['date']
                screening_days += 1

        assert (screening_days == 1 + (prev_date - row['date']).days),\
                f"Expected {screening_days} days, but got {(prev_date - row['date']).days} days"

        last_date_included = prev_date

        if verbose_logging:
            print(f"[{cinema}\t{title}\t{row['date']}]:\tSkip dates up to (incl)\t{last_date_included}\t({screening_days} days)")

        screening_info.append([cinema, row['date'].strftime('%d/%m/%Y'), screening_days, title])

[Искра	«АНГЕЛ В ОТПУСКЕ»	1953-08-04 00:00:00]:	Skip dates up to (incl)	1953-08-04 00:00:00	(1 days)
[Искра	«АНГЕЛ В ОТПУСКЕ»	1953-08-07 00:00:00]:	Skip dates up to (incl)	1953-08-07 00:00:00	(1 days)
[Искра	«АРЕНА СМЕЛЫХ»	1953-08-11 00:00:00]:	Skip dates up to (incl)	1953-08-11 00:00:00	(1 days)
[Искра	«АРЕНА СМЕЛЫХ»	1953-08-13 00:00:00]:	Skip dates up to (incl)	1953-08-14 00:00:00	(2 days)
[Искра	«АРШИН МАЛ АЛАН»	1953-07-03 00:00:00]:	Skip dates up to (incl)	1953-07-03 00:00:00	(1 days)
[Искра	«БЕЛИНСКИЙ»	1953-06-09 00:00:00]:	Skip dates up to (incl)	1953-06-11 00:00:00	(3 days)
[Искра	«В ОДНОМ УНИВЕРМАГЕ»	1953-07-01 00:00:00]:	Skip dates up to (incl)	1953-07-03 00:00:00	(3 days)
[Искра	«ВАРВАРЫ»	1953-07-27 00:00:00]:	Skip dates up to (incl)	1953-07-27 00:00:00	(1 days)
[Искра	«ВАРВАРЫ»	1953-07-31 00:00:00]:	Skip dates up to (incl)	1953-07-31 00:00:00	(1 days)
[Искра	«ДЕВУШКА СПЕШИТ НА СВИДАНИЕ»	1953-08-03 00:00:00]:	Skip dates up to (incl)	1953-08-05 00:00:00	(3 days)
[Искра	«ДИКАЯ БАРА»	1953-06-23 00:00:00]:	Skip dates up to (incl)	1953-06-24 00:00:00	(2 days)
[Искра	«ЗАПОРОЖЕЦ ЗА ДУНАЕМ»	1953-07-31 00:00:00]:	Skip dates up to (incl)	1953-07-31 00:00:00	(1 days)
[Искра	«КЕТО И КОТЭ»	1953-06-18 00:00:00]:	Skip dates up to (incl)	1953-06-18 00:00:00	(1 days)
[Искра	«КОРИЧНЕВАЯ ПАУТИНА»	1953-06-12 00:00:00]:	Skip dates up to (incl)	1953-06-13 00:00:00	(2 days)
[Искра	«ОПАСНОЕ СХОДСТВО»	1953-06-04 00:00:00]:	Skip dates up to (incl)	1953-06-04 00:00:00	(1 days)
[Искра	«ОПАСНОЕ СХОДСТВО»	1953-06-06 00:00:00]:	Skip dates up to (incl)	1953-06-06 00:00:00	(1 days)
[Искра	«ОПАСНОЕ СХОДСТВО»	1953-06-08 00:00:00]:	Skip dates up to (incl)	1953-06-08 00:00:00	(1 days)
[Искра	«ОПЕРАЦИЯ «Б»	1953-08-03 00:00:00]:	Skip dates up to (incl)	1953-08-03 00:00:00	(1 days)
[Искра	«ПЕРВАЯ ПЕРЧАТКА»	1953-06-09 00:00:00]:	Skip dates up to (incl)	1953-06-11 00:00:00	(3 days)
[Искра	«ПОЕЗД ИДЕТ НА ВОСТОК»	1953-06-12 00:00:00]:	Skip dates up to (incl)	1953-06-13 00:00:00	(2 days)
[Искра	«ПРАЗДНИК СВ. ИОРГЕНА»	1953-07-21 00:00:00]:	Skip dates up to (incl)	1953-07-22 00:00:00	(2 days)
[Искра	«СИЛЬВА»	1953-07-16 00:00:00]:	Skip dates up to (incl)	1953-07-17 00:00:00	(2 days)
[Искра	«ТАНКЕР «ДЕРБЕНТ»»	1953-06-23 00:00:00]:	Skip dates up to (incl)	1953-06-24 00:00:00	(2 days)
[Искра	«УЧИТЕЛЬ ТАНЦЕВ» {1-я серия)	1953-08-07 00:00:00]:	Skip dates up to (incl)	1953-08-07 00:00:00	(1 days)
[Искра	«УЧИТЕЛЬ ТАНЦЕВ» {2-я серия)	1953-08-11 00:00:00]:	Skip dates up to (incl)	1953-08-11 00:00:00	(1 days)
[Искра	«ЧЕЛОВЕК В ФУТЛЯРЕ»	1953-07-15 00:00:00]:	Skip dates up to (incl)	1953-07-15 00:00:00	(1 days)
[Искра	«ЧУК И ГЕК»	1953-06-09 00:00:00]:	Skip dates up to (incl)	1953-06-09 00:00:00	(1 days)
[Искра	«ШКОЛА НЕНАВИСТИ»	1953-07-22 00:00:00]:	Skip dates up to (incl)	1953-07-22 00:00:00	(1 days)
[Искра	«ЮНОСТЬ ПОЭТА»	1953-06-08 00:00:00]:	Skip dates up to (incl)	1953-06-08 00:00:00	(1 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-06-01 00:00:00]:	Skip dates up to (incl)	1953-06-02 00:00:00	(2 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-06-04 00:00:00]:	Skip dates up to (incl)	1953-06-04 00:00:00	(1 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-06-06 00:00:00]:	Skip dates up to (incl)	1953-06-06 00:00:00	(1 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-06-09 00:00:00]:	Skip dates up to (incl)	1953-06-13 00:00:00	(5 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-06-15 00:00:00]:	Skip dates up to (incl)	1953-06-15 00:00:00	(1 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-06-18 00:00:00]:	Skip dates up to (incl)	1953-06-19 00:00:00	(2 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-06-22 00:00:00]:	Skip dates up to (incl)	1953-06-25 00:00:00	(4 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-06-27 00:00:00]:	Skip dates up to (incl)	1953-06-27 00:00:00	(1 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-06-30 00:00:00]:	Skip dates up to (incl)	1953-07-01 00:00:00	(2 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-07-03 00:00:00]:	Skip dates up to (incl)	1953-07-03 00:00:00	(1 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-07-06 00:00:00]:	Skip dates up to (incl)	1953-07-06 00:00:00	(1 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-07-15 00:00:00]:	Skip dates up to (incl)	1953-07-17 00:00:00	(3 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-07-21 00:00:00]:	Skip dates up to (incl)	1953-07-24 00:00:00	(4 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-07-27 00:00:00]:	Skip dates up to (incl)	1953-07-27 00:00:00	(1 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-07-31 00:00:00]:	Skip dates up to (incl)	1953-07-31 00:00:00	(1 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-08-03 00:00:00]:	Skip dates up to (incl)	1953-08-07 00:00:00	(5 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-08-11 00:00:00]:	Skip dates up to (incl)	1953-08-11 00:00:00	(1 days)
[Стереокино	«МАЙСКАЯ НОЧЬ»	1953-08-13 00:00:00]:	Skip dates up to (incl)	1953-08-14 00:00:00	(2 days)
[Юный зритель	«АДМИРАЛ УШАКОВ»	1953-07-17 00:00:00]:	Skip dates up to (incl)	1953-07-17 00:00:00	(1 days)
[Юный зритель	«АЛЕКСАНДР НЕВСКИЙ»	1953-07-03 00:00:00]:	Skip dates up to (incl)	1953-07-03 00:00:00	(1 days)
[Юный зритель	«АРЕНА СМЕЛЫХ»	1953-08-11 00:00:00]:	Skip dates up to (incl)	1953-08-11 00:00:00	(1 days)
[Юный зритель	«АРЕНА СМЕЛЫХ»	1953-08-13 00:00:00]:	Skip dates up to (incl)	1953-08-14 00:00:00	(2 days)
[Юный зритель	«АРШИН МАЛ АЛАН»	1953-07-31 00:00:00]:	Skip dates up to (incl)	1953-07-31 00:00:00	(1 days)
[Юный зритель	«БЕЛИНСКИЙ»	1953-06-08 00:00:00]:	Skip dates up to (incl)	1953-06-13 00:00:00	(6 days)
[Юный зритель	«БЕЛЫЙ КЛЫК»	1953-06-09 00:00:00]:	Skip dates up to (incl)	1953-06-09 00:00:00	(1 days)
[Юный зритель	«В ДАЛЬНЕМ ПЛАВАНИИ»	1953-07-06 00:00:00]:	Skip dates up to (incl)	1953-07-06 00:00:00	(1 days)
[Юный зритель	«ВОЗВРАЩЕНИЕ ВАСИЛИЯ БOPTHИКОВА»	1953-07-29 00:00:00]:	Skip dates up to (incl)	1953-07-29 00:00:00	(1 days)
[Юный зритель	«ВОЛШЕБНОЕ ЗЕРНО»	1953-06-30 00:00:00]:	Skip dates up to (incl)	1953-06-30 00:00:00	(1 days)
[Юный зритель	«ГЕОРГИИ  СААКАДЗЕ» (1-я  сер.)	1953-07-21 00:00:00]:	Skip dates up to (incl)	1953-07-23 00:00:00	(3 days)
[Юный зритель	«ГЕОРГИИ СААКАДЗЕ (1-я сер.)	1953-07-24 00:00:00]:	Skip dates up to (incl)	1953-07-24 00:00:00	(1 days)
[Юный зритель	«ДАЛЕКАЯ НЕВЕСТА»	1953-07-16 00:00:00]:	Skip dates up to (incl)	1953-07-16 00:00:00	(1 days)
[Юный зритель	«ДЕТИ КАПИТАНА ГРАНТА»	1953-08-11 00:00:00]:	Skip dates up to (incl)	1953-08-11 00:00:00	(1 days)
[Юный зритель	«ДЕТСТВО ГОРЬКОГО»	1953-06-16 00:00:00]:	Skip dates up to (incl)	1953-06-18 00:00:00	(3 days)
[Юный зритель	«ДЖУЛЬБАРС»	1953-08-07 00:00:00]:	Skip dates up to (incl)	1953-08-07 00:00:00	(1 days)
[Юный зритель	«ЗА СОВЕТСКУЮ РОДИНУ»	1953-08-07 00:00:00]:	Skip dates up to (incl)	1953-08-07 00:00:00	(1 days)
[Юный зритель	«ЗОЛУШКА»	1953-07-23 00:00:00]:	Skip dates up to (incl)	1953-07-24 00:00:00	(2 days)
[Юный зритель	«ИСТРЕБИТЕЛИ»	1953-06-18 00:00:00]:	Skip dates up to (incl)	1953-06-18 00:00:00	(1 days)
[Юный зритель	«КАК ЗАКАЛЯЛАСЬ СТАЛЬ»	1953-08-04 00:00:00]:	Skip dates up to (incl)	1953-08-05 00:00:00	(2 days)
[Юный зритель	«КИНОСБОРНИК МУЛЬТИПЛИКАЦИЙ»	1953-07-03 00:00:00]:	Skip dates up to (incl)	1953-07-03 00:00:00	(1 days)
[Юный зритель	«КОНЕК-ГОРБУНОК»	1953-07-21 00:00:00]:	Skip dates up to (incl)	1953-07-22 00:00:00	(2 days)
[Юный зритель	«МАЛАХОВ КУРГАН»	1953-06-10 00:00:00]:	Skip dates up to (incl)	1953-06-10 00:00:00	(1 days)
[Юный зритель	«МАШЕНЬКА»	1953-06-22 00:00:00]:	Skip dates up to (incl)	1953-06-24 00:00:00	(3 days)
[Юный зритель	«МЫ ИЗ КРОНШТАДТА»	1953-06-29 00:00:00]:	Skip dates up to (incl)	1953-06-29 00:00:00	(1 days)
[Юный зритель	«ОПАСНЫЙ РЕИС»	1953-08-03 00:00:00]:	Skip dates up to (incl)	1953-08-03 00:00:00	(1 days)
[Юный зритель	«ОПЕРАЦИЯ Б.»	1953-07-27 00:00:00]:	Skip dates up to (incl)	1953-07-27 00:00:00	(1 days)
[Юный зритель	«ОСТРОВ COKPОВИЩ»	1953-07-27 00:00:00]:	Skip dates up to (incl)	1953-07-27 00:00:00	(1 days)
[Юный зритель	«ПАХТА-ОЙ»	1953-07-15 00:00:00]:	Skip dates up to (incl)	1953-07-16 00:00:00	(2 days)
[Юный зритель	«ПОВЕСТЬ О НАСТОЯЩЕМ ЧЕЛОВЕКЕ»	1953-07-15 00:00:00]:	Skip dates up to (incl)	1953-07-16 00:00:00	(2 days)
[Юный зритель	«ПОДВИГ РАЗВЕДЧИКА»	1953-08-03 00:00:00]:	Skip dates up to (incl)	1953-08-03 00:00:00	(1 days)
[Юный зритель	«СЕКРЕТАРЬ РАИКОМА»	1953-07-29 00:00:00]:	Skip dates up to (incl)	1953-07-29 00:00:00	(1 days)
[Юный зритель	«СЕКРЕТАРЬ РАЙКОМА»	1953-07-31 00:00:00]:	Skip dates up to (incl)	1953-07-31 00:00:00	(1 days)
[Юный зритель	«СЕМЕРО СМЕЛЫХ»	1953-08-11 00:00:00]:	Skip dates up to (incl)	1953-08-11 00:00:00	(1 days)
[Юный зритель	«СКАЗАНИЕ О ЗЕМЛЕ СИБИРСКОЙ»	1953-08-04 00:00:00]:	Skip dates up to (incl)	1953-08-05 00:00:00	(2 days)
[Юный зритель	«СКАЗАНИЕ О ЗЕМЛЕ СИБИРСКОЙ»	1953-08-07 00:00:00]:	Skip dates up to (incl)	1953-08-07 00:00:00	(1 days)
[Юный зритель	«СЛОН И ВЕРЕВОЧКА»	1953-07-06 00:00:00]:	Skip dates up to (incl)	1953-07-06 00:00:00	(1 days)
[Юный зритель	«ТИМУР И ЕГО КОМАНДА»	1953-08-03 00:00:00]:	Skip dates up to (incl)	1953-08-03 00:00:00	(1 days)
[Юный зритель	«ЦИРК»	1953-06-19 00:00:00]:	Skip dates up to (incl)	1953-06-19 00:00:00	(1 days)
[Юный зритель	«ЧЕТВЕРТЫЙ ПЕРИСКОП»	1953-07-17 00:00:00]:	Skip dates up to (incl)	1953-07-17 00:00:00	(1 days)
[Юный зритель	«ЧОРТОВО УЩЕЛЬЕ»	1953-08-13 00:00:00]:	Skip dates up to (incl)	1953-08-14 00:00:00	(2 days)
[Юный зритель	«ЧУК И ГЕК»	1953-06-02 00:00:00]:	Skip dates up to (incl)	1953-06-03 00:00:00	(2 days)
[Юный зритель	«ЧУК И ГЕК»	1953-06-06 00:00:00]:	Skip dates up to (incl)	1953-06-06 00:00:00	(1 days)
[Юный зритель	«ЧУК И ГЕК»	1953-06-08 00:00:00]:	Skip dates up to (incl)	1953-06-13 00:00:00	(6 days)
[Юный зритель	«ЧУК И ГЕК»	1953-06-16 00:00:00]:	Skip dates up to (incl)	1953-06-16 00:00:00	(1 days)
[Юный зритель	«ЧУК И ГЕК»	1953-06-18 00:00:00]:	Skip dates up to (incl)	1953-06-19 00:00:00	(2 days)
[Юный зритель	«ЧУК И ГЕК»	1953-06-22 00:00:00]:	Skip dates up to (incl)	1953-06-24 00:00:00	(3 days)

In [20]:
def str_to_float(data: pd.DataFrame, *columns_names):
    for column_name in columns_names:
        data[column_name] = data[column_name].astype(str).str.replace(',', '.', regex=False).astype(float)
    return data
    
batch_of_cinemas = ["Искра", "Метрополь", "Орион", "Стереокино", "Ударник", "Юный зритель"] 

cinemas = get_data('./assets/cinemas.csv')
cinemas = cinemas[['Кинотеатр', 'Количество мест', 'Количество сеансов в день', 'Цена билета']]
cinemas = cinemas.rename(columns={'Кинотеатр': 'cinema', 
                            'Количество мест': 'seats', 
                            'Количество сеансов в день': 'avg_day_screen', 
                            'Цена билета': 'price'})

cinemas = str_to_float(cinemas, 'seats', 'avg_day_screen', 'price')
cinemas['day_earnings'] = cinemas['seats'] * cinemas['avg_day_screen'] * cinemas['price']
cinemas[cinemas['cinema'].isin(batch_of_cinemas)]

          cinema   seats  avg_day_screen  price  day_earnings
12         Искра   210.0             8.4   2.80      4939.200
19     Метрополь   692.0             9.4   4.21     27385.208
27         Орион   701.0             8.4   4.50     26497.800
35    Стереокино   166.0             8.4   8.00     11155.200
38       Ударник  1587.0             8.9   4.14     58474.602
49  Юный зритель   361.0             8.4   3.98     12068.952

In [21]:
screening_df = pd.DataFrame(screening_info, columns=['cinema', 'First day of screening', 'Screening Days', 'Title'])
screening_df['Title'] = screening_df['Title'].str.replace('«', '').str.replace('»', '')
screening_df['Title'] = screening_df['Title'].str.title()

screening_df.head()

  cinema First day of screening  Screening Days            Title
0  Искра             04/08/1953               1  Ангел В Отпуске
1  Искра             07/08/1953               1  Ангел В Отпуске
2  Искра             11/08/1953               1     Арена Смелых
3  Искра             13/08/1953               2     Арена Смелых
4  Искра             03/07/1953               1   Аршин Мал Алан

In [22]:
screening_df = screening_df.merge(cinemas[['cinema', 'day_earnings']], on='cinema', how='left')
screening_df = screening_df.rename(columns={'day_earnings':'popstat'})

screening_df['popstat'] = screening_df['popstat'].round(2)
popstat = screening_df.groupby('Title')['popstat'].sum().reset_index().sort_values(by='popstat', ascending=False)
popstat.head()

  cinema First day of screening  Screening Days            Title  popstat
0  Искра             04/08/1953               1  Ангел В Отпуске   4939.2
1  Искра             07/08/1953               1  Ангел В Отпуске   4939.2
2  Искра             11/08/1953               1     Арена Смелых   4939.2
3  Искра             13/08/1953               2     Арена Смелых   4939.2
4  Искра             03/07/1953               1   Аршин Мал Алан   4939.2

In [23]:

if os.path.exists(save_filepath):
    print(f"The save filepath '{save_filepath}' already exists. Either delete it or specify a different save location (See `save_filepath` variable above).")
else:
    print(f"Saving the screening days analysis to '{save_filepath}'")
    os.makedirs('./results', exist_ok=True)
    screening_df.to_csv(save_filepath, index=False)

Saving the screening days analysis to './results/screening.csv'

In [24]:
# save popstat to ./results/popstat.csv
popstat_filepath = './results/popstat.csv'
if os.path.exists(popstat_filepath):
    print(f"The save filepath '{popstat_filepath}' already exists. Either delete it or specify a different save location (See `save_filepath` variable above).")
else:
    print(f"Saving the screening days analysis to '{popstat_filepath}'")
    os.makedirs('./results', exist_ok=True)
    popstat.to_csv(popstat_filepath, index=False)

Saving the screening days analysis to './results/popstat.csv'